### PR TITLE
[Envelope] Ability to have drag points move with start/end points

### PR DESCRIPTION
**Pull request by ffxsam**
We have a use case where the envelope is "attached" to a region, so when the user moves the region, we want the whole envelope to move with it. I realized that the drag points are fixed and immobile, so this PR will add an option for the drag points to move along with the start/end times when those are changed via the API.

### CODE REVIEW

**Comment by katspaugh** [comment]
Not sure I understand why you want `setStartTime` to also move the end time.
Can't you just call `setStartTime` and `setEndTime` successively?

**Comment by ffxsam** [comment]
So, to get into the use case more:

Our customers have the ability to create non-destructible snippets from a full audio track. To do this, they bring up a waveform and drag to select a region. Currently, they can only input a fade in/out time in seconds in a text field. They'd like to be able to do this visually/interactively.

The problem with the plugin right now is that you can set the start/end times but not the drag points. So if a user were to drag the whole region, the drag points don't move with it:

https://user-images.githubusercontent.com/12532733/236479585-a51bff43-1626-4864-bccb-e234b15e741f.mp4

```ts
  regions.on('region-updated', (region) => {
    startTime.value = region.start
    endTime.value = region.end

    envelope.setStartTime(region.start)
    envelope.setEndTime(region.end)
  })
```

**Comment by katspaugh** [comment]
Oh, I see. Your PR makes sense now! Please revert the change in `examples/envelope.js` and we can merge it 👍

**Comment by ffxsam** [comment]
Done!

**Review by katspaugh — APPROVED** [review]
👍

**Comment by ffxsam** [comment]
@katspaugh Woops! I set this PR as a draft because it wasn't done yet. It actually has no effect. I found out that there needs to be some manual SVG tweaking to make the points update.

**Comment by katspaugh** [comment]
My bad, I should’ve tested it. Please feel free to make a follow-up PR then.

**Pull request merged**
