### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by katspaugh**
Add our new logo to the header.

See https://github.com/wavesurfer-js/wavesurfer.js/discussions/2720

Screenshot 2023-03-15 at 08 58 26

### CODE REVIEW

**Comment by entonbiba** [comment]
@katspaugh do you want this as in a reduced size as well? We can then do something like this

```html
<picture>
  <source media="(max-width:700px)" srcset="logo-700w.jpg">
  <source media="(max-width:500px)" srcset="logo-500w.jpg">
  <source media="(max-width:300px)" srcset="logo-300w.jpg">
  <img src="logo.jpg" alt="Wavesurfer.js Logo" style="width:auto;">
</picture>
```

**Comment by katspaugh** [comment]
@entonbiba I think 8kb is pretty small already. JPG is definitely not a good choice for a logo due to aliasing.

**Comment by entonbiba** [comment]
@katspaugh yes it's png and svg let me export it for here

**Review by entonbiba — APPROVED** [review]

**Comment by entonbiba** [comment]
@katspaugh I added a border around the logo, use this one instead and here is the SVG.

Here are the hex codes for the colors:
blue `2fa6fe`
purple `a410a7`
gray `e5eaf7`
white `ffffff`

wavesurferjs-logo

wavesurferjs-logo

**Comment by katspaugh** [comment]
Thanks @entonbiba!

I think a white border looks nicer in the header because it plays nicely with the white text. But the blue border looks great on its own, so we can use that variant in some other contexts in the design.

**Comment by katspaugh** [comment]
@entonbiba I've also adjusted the gradient color in the header and footer to match the logo palette, wdyt?

https://logo.wavesurfer-ts.pages.dev/tutorial/

**Comment by katspaugh** [comment]
Yeah, good idea, kinda like brand colors.

**Comment by katspaugh** [comment]
@entonbiba could you approve the PR?

**Comment by entonbiba** [comment]
@katspaugh done, but i think you added another user to `Reviewers`

**Comment by katspaugh** [comment]
Thanks! And thank you again for reworking the logo!

**Pull request merged**
